# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='action',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, unique=True, verbose_name='Transaction Reference'),
        ),
    ]
